In [5]:
import numpy as np

a = np.array([1,2,3,4])

print(a)

print(np.arange(10))

type(a)

[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [6]:
l = range(1000)
%timeit [i ** 2 for i in l]

651 µs ± 16.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
a = np.arange(1000)
%timeit a ** 2

6.21 µs ± 53.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [9]:
a.ndim

1

In [10]:
a.shape

(3,)

In [11]:
 len(a)

3

In [13]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
b.ndim

2

In [15]:
b.shape

(2, 3)

In [16]:
len(b)

2

In [17]:
c = np.array([ [ [1,2],[5,6] ]  , [ [8,3], [7,8] ] ])

In [18]:
c

array([[[1, 2],
        [5, 6]],

       [[8, 3],
        [7, 8]]])

In [19]:
c.ndim

3

In [20]:
c.shape

(2, 2, 2)

In [24]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
b = np.arange(2,19,3)
b

array([ 2,  5,  8, 11, 14, 17])

In [29]:
c = np.linspace(0,10,5)
c

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
a = np.ones((3,3))

In [31]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
b = np.zeros((3,3))

In [33]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [38]:
np.diag(a)

array([1, 2, 3, 4])

In [39]:
a = np.random.rand(5)
a

array([0.6128767 , 0.02636687, 0.62020316, 0.53749672, 0.2132069 ])

In [41]:
b = np.random.randn(8)
b

array([ 1.00931635,  0.99148111,  0.38829386,  0.45185801,  1.26700972,
       -0.16580093, -1.17931424, -1.23886089])

In [42]:
a = np.arange(10)
a.dtype

dtype('int32')

In [43]:
a = np.arange(10, dtype = 'float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [44]:
a = np.zeros((4,4))
print(a)
a.dtype

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


dtype('float64')

In [45]:
d = np.array([1+2j, 2+4j])
d.dtype

dtype('complex128')

In [48]:
b = np.array([True, False])
print(b)
b.dtype

[ True False]


dtype('bool')

In [49]:
c = np.array(['mohit'])
c.dtype

dtype('<U5')

In [51]:
a = np.arange(10)
print(a)
a[5]

[0 1 2 3 4 5 6 7 8 9]


5

In [53]:
c = [1,2,3,4,5]
c[4]

5

In [54]:
a = np.diag([1,2,3] )
print(a)
print(a[2,2])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [55]:
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [56]:
a[2,2] = 4

a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 4]])

In [57]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
a[1:8:2]

array([1, 3, 5, 7])

In [59]:
a[5:]

array([5, 6, 7, 8, 9])

In [62]:
a[5:] = 10

In [63]:
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [77]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [78]:
b[:-1]

array([0, 1, 2, 3])

In [79]:
b

array([0, 1, 2, 3, 4])

In [80]:
b[::-1]

array([4, 3, 2, 1, 0])

In [81]:
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [82]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [85]:
np.shares_memory(a,b)

True

In [86]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [87]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [88]:
np.shares_memory(a,b)

True

In [90]:
a = np.arange(10)

c = a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [91]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
c[2] = 10
c

array([ 0,  2, 10,  6,  8])

In [93]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
np.shares_memory(a,c)

False

In [95]:
a = np.random.randint(0,20,15)
a

array([ 0,  7, 15,  3, 14,  3, 11,  7, 15,  8, 17, 19,  3, 18,  4])

In [97]:
mask = (a%2 == 0)

In [98]:
mask

array([ True, False, False, False,  True, False, False, False, False,
        True, False, False, False,  True,  True])

In [99]:
extraxt_from_a = a[mask]

In [101]:
extraxt_from_a

array([ 0, 14,  8, 18,  4])

In [104]:
a[mask] = -1 
# all even no. converts to -1

In [105]:
a

array([-1,  7, 15,  3, -1,  3, 11,  7, 15, -1, 17, 19,  3, -1, -1])

In [106]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [107]:
a[[2,3,2,3,4,2]]

array([20, 30, 20, 30, 40, 20])

In [109]:
a[[5,7]] = -200
a

array([   0,   10,   20,   30,   40, -200,   60, -200,   80, -200])